In [1]:
# Load initial data for processing
import pandas as pd
df = pd.read_csv("C:\\Users\\k1332\\MapReduce-House-Weather\\Converted-House-data.csv")
df.head()

C:\Users\k1332\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3058: DtypeWarning: Columns (2,5,8,11,14,23,29,30,32) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,OBJECTID,PlanningAuthority,ApplicationNumber,DevelopmentDescription,DevelopmentAddress,DevelopmentPostcode,ITMEasting,ITMNorthing,ApplicationStatus,ApplicationType,...,AppealSubmittedDate,FIRequestDate,FIRecDate,LinkAppDetails,OneOffKPI,ETL_DATE,SiteId,Shape__Area,Shape__Length,county
0,1,Carlow,101,"to erect a two storey dwellinmg house, garage,...","Ballybannon , Milford , Co. Carlow",NaN,NaN,NaN,APPLICATION FINALISED,PERMISSION,...,NaN,NaN,NaN,http://www.eplanning.ie/CarlowCC/AppFileRefDet...,Yes,2019-11-05T00:00:00.000Z,10970,8471.329102,368.599644,Carlow
1,2,Carlow,102,construction of a canopy to shelter existing s...,"Leighlinbridge Road , Bagenalstown , Co. Carlow",NaN,NaN,NaN,APPLICATION FINALISED,PERMISSION,...,NaN,NaN,NaN,http://www.eplanning.ie/CarlowCC/AppFileRefDet...,No,2019-11-05T00:00:00.000Z,10971,612.755859,212.031192,Carlow
2,6,Carlow,103,Alterations to elevation/roof at existing sheds,"Killamaster , Co. Carlow",NaN,NaN,NaN,INCOMPLETED APPLICATION,PERMISSION,...,NaN,NaN,NaN,http://www.eplanning.ie/CarlowCC/AppFileRefDet...,No,2019-11-05T00:00:00.000Z,10975,32137.373047,732.248322,Carlow
3,13,Carlow,104,extensions and alterations to Spellman Hall,"Kildavin , Co. Carlow",NaN,NaN,NaN,APPLICATION FINALISED,PERMISSION,...,NaN,NaN,NaN,http://www.eplanning.ie/CarlowCC/AppFileRefDet...,No,2019-11-05T00:00:00.000Z,10982,5399.716797,306.453618,Carlow
4,1483,Carlow,106301,The proposed development comprises a retail su...,"Carlow Retail Park , Hanover , Carlow",NaN,NaN,NaN,APPLICATION FINALISED,PERMISSION,...,2010-06-23T00:00:00.000Z,2010-03-03T00:00:00.000Z,2010-03-30T00:00:00.000Z,http://www.eplanning.ie/CarlowCC/AppFileRefDet...,No,2019-11-05T00:00:00.000Z,13773,148313.367188,2696.219269,Carlow

In [2]:
# check the column names of the Dataset
print("The Column names of the dataset")
df.columns

The Column names of the dataset

Index(['OBJECTID', 'PlanningAuthority', 'ApplicationNumber',
       'DevelopmentDescription', 'DevelopmentAddress', 'DevelopmentPostcode',
       'ITMEasting', 'ITMNorthing', 'ApplicationStatus', 'ApplicationType',
       'Decision', 'LandUseCode', 'AreaofSite', 'NumResidentialUnits',
       'OneOffHouse', 'FloorArea', 'ReceivedDate', 'WithdrawnDate',
       'DecisionDate', 'DecisionDueDate', 'GrantDate', 'ExpiryDate',
       'AppealRefNumber', 'AppealStatus', 'AppealDecision',
       'AppealDecisionDate', 'AppealSubmittedDate', 'FIRequestDate',
       'FIRecDate', 'LinkAppDetails', 'OneOffKPI', 'ETL_DATE', 'SiteId',
       'Shape__Area', 'Shape__Length', 'county'],
      dtype='object')

In [3]:
# Select the columns that we need to use.
columns = ['PlanningAuthority','Decision','ReceivedDate','DecisionDate','GrantDate','Shape__Area','Shape__Length']
df_sub = df[columns]
df_sub.head()

,PlanningAuthority,Decision,ReceivedDate,DecisionDate,GrantDate,Shape__Area,Shape__Length
0,Carlow,CONDITIONAL,2010-01-04T00:00:00.000Z,2010-02-24T00:00:00.000Z,2010-03-29T00:00:00.000Z,8471.329102,368.599644
1,Carlow,CONDITIONAL,2010-01-04T00:00:00.000Z,2010-02-24T00:00:00.000Z,2010-03-29T00:00:00.000Z,612.755859,212.031192
2,Carlow,NaN,2010-01-07T00:00:00.000Z,NaN,NaN,32137.373047,732.248322
3,Carlow,CONDITIONAL,2010-01-08T00:00:00.000Z,2010-02-25T00:00:00.000Z,2010-03-30T00:00:00.000Z,5399.716797,306.453618
4,Carlow,CONDITIONAL,2010-01-08T00:00:00.000Z,2010-06-01T00:00:00.000Z,NaN,148313.367188,2696.219269

In [4]:
# Check the data types of each columns
df_sub.dtypes

PlanningAuthority     object
Decision              object
ReceivedDate          object
DecisionDate          object
GrantDate             object
Shape__Area          float64
Shape__Length        float64
dtype: object

In [5]:
import numpy as np

# Get unique values of PlanningAuthority Column
np.unique(list(df_sub['PlanningAuthority'].values))

array(['Carlow', 'Cavan', 'Clare', 'Cork', 'Donegal', 'Dublin',
       'DunLaoghaireRathdown', 'Fingal', 'Galway', 'Kerry', 'Kildare',
       'Kilkenny', 'Laois', 'Leitrim', 'Limerick', 'Longford', 'Louth',
       'Mayo', 'Meath', 'Monaghan', 'Offaly', 'Roscommon', 'Sligo',
       'Tipperary', 'Waterford', 'Wexford', 'Wicklow'], dtype='<U20')

In [6]:
# Get unique values of Decision Column
np.unique(list(df_sub['Decision'].values))

array([' ', 'ADDITIONAL INFORMATION', 'APPLICATION DECLARED INVALID',
       'APPLICATION WITHDRAWN', 'APPLICATION WITHDRAWN ON APPEAL',
       'APPROVAL FOR THE PROPOSAL TO PROCEED    ',
       'APPROVE COMPLIANCE SUBMITTED',
       'APPROVE COMPLIANCE SUBMITTED            ',
       'APPROVE/DISAPPROVE COMPLIANCE SUBMITTED', 'Additions/Revisions',
       'App withdrawn as no AI recd in 6 months           ',
       'App. withdrawn as no C.AI recd in 6 mths          ', 'C',
       'CANNOT BE CONSIDERED', 'CANNOT DETERMINE',
       'CLARIFICATION OF ADDITIONAL INFORMATION',
       'CLARIFICATION OF FURTHER INFORMATION    ', 'CONDITIONAL',
       'Conditional Permission', 'DECLARE APPLICATION INVALID',
       'DECLARE APPLICATION INVALID             ',
       'DECLARE APPLICATION WITHDRAWN',
       'DECLARE APPLICATION WITHDRAWN           ',
       'DECLARE APPLICATION WITHDRAWN (AI Not Re',
       'DECLARE INVALID (SITE NOTICE)',
       'DECLARE INVALID (SITE NOTICE)           ', 'DECLARED WITHDRAWN',
       'Ext Dur no ai recd 1mth WD                        ',
       'GRANT APPROVAL', 'GRANT APPROVAL                          ',
       'GRANT EXTENSION OF DURATION OF PERM.',
       'GRANT EXTENSION OF DURATION OF PERM.    ',
       'GRANT EXTENSION OF DURATION OF PERM.              ',
       'GRANT EXTENSION OF DURATION OF PERMISSION',
       'GRANT FURTHER EXT. OF DURATION OF PERM. ',
       'GRANT FURTHER EXT. OF DURATION OF PERM.           ',
       'GRANT FURTHER EXT. OF DURATION OF PERMISSION',
       'GRANT OUTLINE PERM. & REFUSE OUTLINE PERM.',
       'GRANT OUTLINE PERMISSION',
       'GRANT OUTLINE PERMISSION                ',
       'GRANT OUTLINE PERMISSION                          ',
       'GRANT PER. REFU. PERM. GRAT. RETENTION            ',
       'GRANT PERM. CONSEQUENT TO OUTLINE PERM.           ',
       'GRANT PERMISSION', 'GRANT PERMISSION                        ',
       'GRANT PERMISSION                                  ',
       'GRANT PERMISSION & APPROVAL',
       'GRANT PERMISSION & GRANT OUTLINE PERM.',
       'GRANT PERMISSION & GRANT OUTLINE PERM.            ',
       'GRANT PERMISSION & GRANT RETENTION',
       'GRANT PERMISSION & GRANT RETENTION      ',
       'GRANT PERMISSION & GRANT RETENTION                ',
       'GRANT PERMISSION & REFUSE PERMISSION',
       'GRANT PERMISSION & REFUSE PERMISSION    ',
       'GRANT PERMISSION & REFUSE PERMISSION              ',
       'GRANT PERMISSION & REFUSE RETENTION',
       'GRANT PERMISSION AND RETENTION PERMISSION',
       'GRANT PERMISSION CONSEQUENT TO OUTLINE',
       'GRANT PERMISSION CONSEQUENT TO OUTLINE  ',
       'GRANT PERMISSION FOLLOWING OUTLINE',
       'GRANT PERMISSION FOR RETENTION',
       'GRANT PERMISSION FOR RETENTION          ',
       'GRANT PERMISSION FOR RETENTION                    ',
       'GRANT RETENTION', 'GRANT RETENTION & REFUSE PERMISSION',
       'GRANT RETENTION & REFUSE PERMISSION               ',
       'GRANT RETENTION & REFUSE RETENTION',
       'GRANT RETENTION & REFUSE RETENTION & REFUSE PERMISSION',
       'GRANT RETENTION PERM & REFUSE RETENTION ',
       'GRANT RETENTION PERMISSION',
       'GRANT TIME EXT (3 months) AI                      ',
       'GRNT AND REF PER.,GRANT AND REF. RETENT           ',
       'Grant Perm & Retention and Refuse Retent          ',
       'Grant Permission & Refuse Retention               ',
       'Grant Retention & Refuse Retention                ',
       'Grant with Social Housing Condition', 'Granted (Conditional)',
       'Granted (Unconditional)', 'INVALID - SITE NOTICE',
       'INVALID APPLICATION',
       'INVALID APPLICATION DUE TO SITE NOTICE            ',
       'INVALID PLANNING APPLICATION                      ',
       'INVALIDATE APPLICATION', 'Invalid Application (site notice)',
       'OUTLINE PERMISSION GRANTED',
       'PAC REPORT & FILE CLOSED                ',
       'PART 8 APPROVED BY COUNCIL', 'PART 8 REJECTED BY COUNCIL', 'R',
       'REFUSE APPROVAL', 'REFUSE EXT. OF DURATION OF PERMISSION',
       'REFUSE EXT. OF DURATION OF PERMISSION   ',
       'REFUSE EXT. OF DURATION OF PERMISSION             ',
       'REFUSE FURTHER EXT. OF DURATION OF PERM.',
       'REFUSE FURTHER EXT. OF DURATION OF PERM.          ',
       'REFUSE OUTLINE PERMISSION',
       'REFUSE OUTLINE PERMISSION               ',
       'REFUSE OUTLINE PERMISSION                         ',
       'REFUSE PERM. CONSEQUENT TO OUTLINE PERM.          ',
       'REFUSE PERMISSION', 'REFUSE PERMISSION                       ',
       'REFUSE PERMISSION                                 ',
       'REFUSE PERMISSION & GRANT RETENTION',
       'REFUSE PERMISSION & GRANT RETENTION               ',
       'REFUSE PERMISSION & REFUSE OUTLINE PERM.',
       'REFUSE PERMISSION & REFUSE OUTLINE PERM.          ',
       'REFUSE PERMISSION & REFUSE RETENTION',
       'REFUSE PERMISSION & REFUSE RETENTION              ',
       'REFUSE PERMISSION CONSEQUENT TO OUTLINE',
       'REFUSE PERMISSION CONSEQUENT TO OUTLINE ',
       'REFUSE PERMISSION FOLLOWING OUTLINE',
       'REFUSE PERMISSION FOR RETENTION',
       'REFUSE PERMISSION FOR RETENTION         ',
       'REFUSE PERMISSION FOR RETENTION                   ',
       'REFUSE RETENTION PERMISSION', 'REFUSED',
       'REQUEST ADDITIONAL INFORMATION',
       'REQUEST ADDITIONAL INFORMATION          ',
       'REQUEST ADDITIONAL INFORMATION                    ',
       'REQUEST AI EXT OF TIME', 'REQUEST FURTHER PARTICULARS',
       'REQUEST REVISED NEWSPAPER NOTICE',
       'REQUEST REVISED PUBLIC NOTICE', 'REQUEST TIME EXTENSION',
       'Refused', 'Report Returned to An Bord Pleanala',
       'Returned Application under Section 37(5)          ',
       'SEEK CLARIFICATION OF ADDITIONAL INFO.',
       'SEEK CLARIFICATION OF ADDITIONAL INFO.            ',
       'SPLIT DECISION                          ',
       'SPLIT DECISION(PERMISSION & REFUSAL)',
       'SPLIT DECISION(RETENTION PERMISSION)', 'Split decision',
       'TIME EXTENSION FOR FIRE CERT. DECISION', 'UNCONDITIONAL',
       'Unconditional Permission',
       'WITHDRAW APPLICATION                              ',
       'WITHDRAW APPLICATION(SEC 140(1)(B))', 'WITHDRAW THE APPLICATION',
       'WITHDRAW THE APPLICATION                ',
       'WITHDRAWN ARTICLE 33 (NO SUB)',
       'WITHDRAWN ARTICLE 33 (SUBSECTION 4)', 'nan'], dtype='<U54')

In [7]:
print(len(df_sub))

389898

In [8]:
df_sub = df_sub.dropna(axis=0, subset=['Decision'])
print(len(df_sub))

319581

In [9]:
#convert conditional, grant permission to approved
#convert refuse approval and withdrawn applications into disapproved
target = ['CONDITIONAL','Conditional Permission','C','GRANT PERMISSION','GRANT PERMISSION                        ',
         'GRANT PERMISSION                                  ']
for i in range(len(df_sub)):
    if df_sub['Decision'].iloc[i] in target:
        df_sub['Decision'].iloc[i] = 'approved'
    else:
        df_sub['Decision'].iloc[i] = 'disapproved'
        
np.unique(list(df_sub['PlanningAuthority'].values))

C:\Users\k1332\Anaconda3\lib\site-packages\pandas\core\indexing.py:205: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)

array(['Carlow', 'Cavan', 'Clare', 'Cork', 'Donegal', 'Dublin',
       'DunLaoghaireRathdown', 'Fingal', 'Galway', 'Kerry', 'Kildare',
       'Kilkenny', 'Laois', 'Leitrim', 'Limerick', 'Longford', 'Louth',
       'Mayo', 'Meath', 'Monaghan', 'Offaly', 'Roscommon', 'Sligo',
       'Tipperary', 'Waterford', 'Wexford', 'Wicklow'], dtype='<U20')

In [10]:
np.unique(list(df_sub['Decision'].values))

array(['approved', 'disapproved'], dtype='<U11')

In [11]:
# Make new column as depending the seasons of datetime.
df_sub = df_sub.dropna(axis=0, subset=['ReceivedDate'])
df_sub['ReceivedDate'] = pd.to_datetime(df_sub['ReceivedDate'])
lb_list = []
spring = ['03','04','05']
summer = ['06','07','08']
autumn = ['09','10','11']
winter = ['12','01','02']
          
for i in range(len(df_sub)):
    try:
        if str(df_sub['ReceivedDate'][i])[5:7] in spring:
              lb_list.append('spring')
        elif str(df_sub['ReceivedDate'][i])[5:7] in summer:
              lb_list.append('summer')
        elif str(df_sub['ReceivedDate'][i])[5:7] in autumn:
              lb_list.append('autumn')
        elif str(df_sub['ReceivedDate'][i])[5:7] in winter:
              lb_list.append('winter')
    except:
        lb_list.append('Nan')
print(len(lb_list))
df_sub['Seasons'] = lb_list
np.unique(list(df_sub['Seasons'].values))

319578

array(['Nan', 'autumn', 'spring', 'summer', 'winter'], dtype='<U6')

In [12]:
df_sub = df_sub[df_sub.Seasons != 'Nan']
np.unique(list(df_sub['Seasons'].values))

array(['autumn', 'spring', 'summer', 'winter'], dtype='<U6')

In [13]:
df_sub.head()

,PlanningAuthority,Decision,ReceivedDate,DecisionDate,GrantDate,Shape__Area,Shape__Length,Seasons
0,Carlow,approved,2010-01-04 00:00:00+00:00,2010-02-24T00:00:00.000Z,2010-03-29T00:00:00.000Z,8471.329102,368.599644,winter
1,Carlow,approved,2010-01-04 00:00:00+00:00,2010-02-24T00:00:00.000Z,2010-03-29T00:00:00.000Z,612.755859,212.031192,winter
4,Carlow,approved,2010-01-08 00:00:00+00:00,2010-06-01T00:00:00.000Z,NaN,148313.367188,2696.219269,winter
5,Carlow,approved,2010-01-11 00:00:00+00:00,2010-05-17T00:00:00.000Z,2010-06-17T00:00:00.000Z,23114.769043,609.782115,winter
11,Carlow,approved,2010-01-19 00:00:00+00:00,2010-03-11T00:00:00.000Z,2010-04-13T00:00:00.000Z,791.980957,114.109660,winter

In [15]:
df_sub['DecisionDate'] = pd.to_datetime(df_sub['DecisionDate'])
# Get year and month and date values from the full date time format values
df_sub['DecisionDate'] = df_sub['DecisionDate'].dt.date
df_sub.head()
df_sub.to_csv("df_sub_house.csv")

In [27]:
import pandas as pd
df_sub = pd.read_csv("/Users/atandaridwan/Desktop/DIA-Project/df_sub_house.csv")

In [26]:
print(len(df_sub))

265350

In [17]:
df_sub['GrantDate'] = pd.to_datetime(df_sub['GrantDate'], errors='coerce')
df_sub['ReceivedDate'] = pd.to_datetime(df_sub['ReceivedDate'],errors='coerce')

In [18]:
df_sub = df_sub.dropna(axis=0, subset=['GrantDate'])
try:
    df_sub['GrantDate'] = pd.to_datetime(df_sub['GrantDate'])
    
except:
    pass
try:
    df_sub['GrantDate'] = df_sub['GrantDate'].dt.date
    df_sub['ReceivedDate'] = df_sub['ReceivedDate'].dt.date
except:
    pass
df_sub.head()

,Unnamed: 0,PlanningAuthority,Decision,ReceivedDate,DecisionDate,GrantDate,Shape__Area,Shape__Length,Seasons
0,0,Carlow,approved,2010-01-04,2010-02-24,2010-03-29,8471.329102,368.599644,winter
1,1,Carlow,approved,2010-01-04,2010-02-24,2010-03-29,612.755859,212.031192,winter
3,5,Carlow,approved,2010-01-11,2010-05-17,2010-06-17,23114.769043,609.782115,winter
4,11,Carlow,approved,2010-01-19,2010-03-11,2010-04-13,791.980957,114.109660,winter
5,23,Carlow,approved,2010-01-29,2010-03-11,2010-04-13,5897.662109,392.536803,winter

In [19]:
df_sub['GrantDate'].iloc[1000]

datetime.date(2017, 1, 10)

In [20]:
df_sub['DecisionDate'] = pd.to_datetime(df_sub['DecisionDate'],errors='coerce')
df_sub['ReceivedDate'] = pd.to_datetime(df_sub['ReceivedDate'],errors='coerce')
#df_sub['DecisionDate'] = df_sub['DecisionDate'].dt.date
df_sub['Time of Processing'] = df_sub['DecisionDate'] - df_sub['ReceivedDate']
df_sub.head()

,Unnamed: 0,PlanningAuthority,Decision,ReceivedDate,DecisionDate,GrantDate,Shape__Area,Shape__Length,Seasons,Time of Processing
0,0,Carlow,approved,2010-01-04,2010-02-24,2010-03-29,8471.329102,368.599644,winter,51 days
1,1,Carlow,approved,2010-01-04,2010-02-24,2010-03-29,612.755859,212.031192,winter,51 days
3,5,Carlow,approved,2010-01-11,2010-05-17,2010-06-17,23114.769043,609.782115,winter,126 days
4,11,Carlow,approved,2010-01-19,2010-03-11,2010-04-13,791.980957,114.109660,winter,51 days
5,23,Carlow,approved,2010-01-29,2010-03-11,2010-04-13,5897.662109,392.536803,winter,41 days

In [21]:
df_sub = df_sub.drop(columns = ["Unnamed: 0"])
df_sub.head()

,PlanningAuthority,Decision,ReceivedDate,DecisionDate,GrantDate,Shape__Area,Shape__Length,Seasons,Time of Processing
0,Carlow,approved,2010-01-04,2010-02-24,2010-03-29,8471.329102,368.599644,winter,51 days
1,Carlow,approved,2010-01-04,2010-02-24,2010-03-29,612.755859,212.031192,winter,51 days
3,Carlow,approved,2010-01-11,2010-05-17,2010-06-17,23114.769043,609.782115,winter,126 days
4,Carlow,approved,2010-01-19,2010-03-11,2010-04-13,791.980957,114.109660,winter,51 days
5,Carlow,approved,2010-01-29,2010-03-11,2010-04-13,5897.662109,392.536803,winter,41 days

In [23]:
mask = (df_sub['ReceivedDate'] > '2010-01-01') & (df_sub['ReceivedDate'] <= '2019-12-31')
df_sub = df_sub.loc[mask]

In [24]:
print(len(df_sub))

136171

In [45]:
df_sub.to_csv("final_house_planning_data.csv")

# Final Step For the Data Preparing

In [1]:
# load data for final processing
import pandas as pd
df = pd.read_csv("C:\\Users\\k1332\\MapReduce-House-Weather\\final_house_planning_data.csv")
df.head()

,Unnamed: 0,PlanningAuthority,Decision,ReceivedDate,DecisionDate,GrantDate,Shape__Area,Shape__Length,Seasons,Time of Processing
0,0,Carlow,approved,2010-01-04,2010-02-24,2010-03-29,8471.329102,368.599644,winter,51 days 00:00:00.000000000
1,1,Carlow,approved,2010-01-04,2010-02-24,2010-03-29,612.755859,212.031192,winter,51 days 00:00:00.000000000
2,3,Carlow,approved,2010-01-11,2010-05-17,2010-06-17,23114.769043,609.782115,winter,126 days 00:00:00.000000000
3,4,Carlow,approved,2010-01-19,2010-03-11,2010-04-13,791.980957,114.109660,winter,51 days 00:00:00.000000000
4,5,Carlow,approved,2010-01-29,2010-03-11,2010-04-13,5897.662109,392.536803,winter,41 days 00:00:00.000000000

In [2]:
# Select necessary columns for the final data.
df_final = df[['PlanningAuthority','Decision','GrantDate','Time of Processing']]
df_final.head()

  PlanningAuthority  Decision   GrantDate           Time of Processing
0            Carlow  approved  2010-03-29   51 days 00:00:00.000000000
1            Carlow  approved  2010-03-29   51 days 00:00:00.000000000
2            Carlow  approved  2010-06-17  126 days 00:00:00.000000000
3            Carlow  approved  2010-04-13   51 days 00:00:00.000000000
4            Carlow  approved  2010-04-13   41 days 00:00:00.000000000

In [3]:
# cut and replace the final numerical values from the stirng values of "Time of Processing"
for i in range(len(df_final)):
    df_final['Time of Processing'][i] = str(df_final['Time of Processing'][i]).split(' ')[0]
df_final.head()

C:\Users\k1332\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3326: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  exec(code_obj, self.user_global_ns, self.user_ns)

  PlanningAuthority  Decision   GrantDate Time of Processing
0            Carlow  approved  2010-03-29                 51
1            Carlow  approved  2010-03-29                 51
2            Carlow  approved  2010-06-17                126
3            Carlow  approved  2010-04-13                 51
4            Carlow  approved  2010-04-13                 41

In [4]:
# check the types of each columns
df_final.dtypes

PlanningAuthority     object
Decision              object
GrantDate             object
Time of Processing    object
dtype: object

In [5]:
# convert object type to datatime format as default
df_final['GrantDate'] = pd.to_datetime(df_final['GrantDate'])

C:\Users\k1332\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [6]:
# convert the data type to the numberic
df_final = df_final.dropna(subset=['Time of Processing'])
try:
    df_final['Time of Processing'].astype(str).astype(int)
except:
    pass

In [7]:
df_final.dtypes

PlanningAuthority             object
Decision                      object
GrantDate             datetime64[ns]
Time of Processing            object
dtype: object

In [8]:
idx_list = []
for i in range(len(df_final)):
    if float(df_final['Time of Processing'][i]) >= 0:
        idx_list.append(i)
print(len(df_final))
print(len(idx_list))

136171
135754

In [9]:
df_final = df_final.ix[idx_list]
print(len(df_final))
df_final = df_final.reset_index()
df_final.head()

135754

C:\Users\k1332\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.

   index PlanningAuthority  Decision  GrantDate Time of Processing
0      0            Carlow  approved 2010-03-29                 51
1      1            Carlow  approved 2010-03-29                 51
2      2            Carlow  approved 2010-06-17                126
3      3            Carlow  approved 2010-04-13                 51
4      4            Carlow  approved 2010-04-13                 41

In [10]:
df_final = df_final[['GrantDate','PlanningAuthority','Decision','Time of Processing']]
df_final.tail()

        GrantDate PlanningAuthority  Decision Time of Processing
135749 2019-11-05           Wicklow  approved                 48
135750 2019-11-05           Wicklow  approved                 44
135751 2019-11-05           Wicklow  approved                 46
135752 2019-10-21           Wicklow  approved                 35
135753 2019-11-04           Wicklow  approved                 39

In [11]:
# save the dataframe to the final csv file
df_final.to_csv("Final_House.csv", index = False)